// Banco de dados dos produtos

const data = [
  {
    id: 1,
    img: "../img/E-33dlfWEAcqNFM.jpeg",
    nameItem: "God Of War Ragnarök",
    description: "Embarque em uma jornada épica e comovente onde Kratos e Atreus lutam entre o desejo de manterem-se unidos ou separar-se...",
    value: 299.99,
    addCart: "Adicionar ao carrinho",
    tag: ["PlayStation"],
  },
  {
    id: 2,
    img: "../img/images-game.jpeg",
    nameItem: "Horizon Forbidden West",
    description:"A terra está morrendo; tempestades implacáveis e uma praga incontrolável devastam o que sobrou da humanidade,Cabe a Aloy descobrir ...",
    value: 155.90,
    addCart: "Adicionar ao carrinho",
    tag: ["PlayStation"],
  },
  {
    id: 3,
    img: "../img/download-game.jpeg",
    nameItem: "The Last of Us Part II",
    description:"Cinco anos depois da jornada perigosa pelos Estados Unidos pós-pandêmicos, Ellie e Joel se estabelecem em Jackson, Wyoming...",
    value: 143.10,
    addCart: "Adicionar ao carrinho",
    tag: ["PlayStation"],
  },
  {
    id: 4,
    img: "../img/download-game-2.jpeg",
    nameItem: "A Plague Tale: Requiem",
    description:"Depois de escapar de sua terra natal devastada, Amicia e Hugo viajam para o sul, para novas regiões e cidades vibrantes. Lá, eles tentam...",
    value: 320.99,
    addCart: "Adicionar ao carrinho",
    tag: ["Xbox"],
  },
  {
    id: 5,
    img: "../img/images-game-2.jpeg",
    nameItem: "Elden Ring",
    description:"Exploração do mundo nas Terras Intermédias: ELDEN RING apresenta vastos cenários fantásticos e complexas e escuras masmorras...",
    value: 209.59,
    addCart: "Adicionar ao carrinho",
    tag: ["Xbox"],
  },
  {
    id: 6,
    img: "../img/download-game-3 (2).jpeg",
    nameItem:"Call of Duty: Modern Warfare II",
    description:"Bem-vindo à nova era de Call of Duty Apresentando o retorno do icônico líder de equipe Capitão John Price ...",
    value: 317.51,
    addCart: "Adicionar ao carrinho",
    tag: ["Xbox"],
  },
  {
    id: 7,
    img: "../img/download-game-4.jpeg",
    nameItem: "Pokémon Legends: Arceus",
    description:"Prepare-se para uma nova grande aventura Pokémon em Pokémon Legends: Arceus, um jogo totalmente novo da Game Freak ...",
    value: 299.00,
    addCart: "Adicionar ao carrinho",
    tag: ["Nintendo"],
  },
  {
    id: 8,
    img: "../img/download-game-5.jpeg",
    nameItem: "Xenoblade Chronicles 3",
    description:"Junte-se a Noah e Mio, membros das duas nações opostas de Keves e Agnus, em uma jornada emocionante por um mundo em guerra...",
    value: 320.00,
    addCart: "Adicionar ao carrinho",
    tag: ["Nintendo"],
  },
  {
    id: 9,
    img: "../img/download-game-6.jpeg",
    nameItem: "The Legend of Zelda: Breath of the Wild",
    description:
      "Esqueça tudo que você sabe sobre os jogos da série The Legend of Zelda. Entre em um mundo de descobertas...",
    value: 260.66,
    addCart: "Adicionar ao carrinho",
    tag: ["Nintendo"],
  },
];
